### ISSUE TITLE
Error on compile - RBAC

### ISSUE THREAD

**Issue by iamreyne** [mindsear/TemplateNPC#1]
RBAC throws back an error that there is nothing for the reload_template_npc command in RBAC.h

Still isn't working after manually adding code in RBAC.h

**Comment by mindsear** [comment]
I'm sorry if this is too late.

> 

**UPDATE**: You must edit Rbac.h found in TrinityCore\src\server\game\Accounts
Right above RBAC_PERM_MAX add

    // custom permissions 1000+
    RBAC_PERM_COMMAND_RELOAD_TEMPLATE_NPC                    = 1019, 

>
