### ISSUE TITLE
COuld you update this for the newest TC?

### ISSUE THREAD

**Issue by Psilovybin** [mindsear/TemplateNPC#3]
Everything went good up until the last when it couldn't add the different containers for horde or alliance

`[ 98%] Linking CXX executable worldserver
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../scripts/libscripts.a(cs_reload.cpp.o): in function `reload_commandscript::HandleReloadTemplateNPCCommand(ChatHandler*, char const*)':
/home/mangos/trinitycore3.3.5/TrinityCore/src/server/scripts/Commands/cs_reload.cpp:1217: undefined reference to `sTemplateNPC::LoadTalentsContainer()'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/mangos/trinitycore3.3.5/TrinityCore/src/server/scripts/Commands/cs_reload.cpp:1218: undefined reference to `sTemplateNPC::LoadGlyphsContainer()'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/mangos/trinitycore3.3.5/TrinityCore/src/server/scripts/Commands/cs_reload.cpp:1219: undefined reference to `sTemplateNPC::LoadHumanGearContainer()'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/mangos/trinitycore3.3.5/TrinityCore/src/server/scripts/Commands/cs_reload.cpp:1220: undefined reference to `sTemplateNPC::LoadAllianceGearContainer()'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/mangos/trinitycore3.3.5/TrinityCore/src/server/scripts/Commands/cs_reload.cpp:1221: undefined reference to `sTemplateNPC::LoadHordeGearContainer()'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../game/libgame.a(World.cpp.o): in function `World::SetInitialWorldSettings()':
/home/mangos/trinitycore3.3.5/TrinityCore/src/server/game/World/World.cpp:2143: undefined reference to `sTemplateNPC::LoadTalentsContainer()'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/mangos/trinitycore3.3.5/TrinityCore/src/server/game/World/World.cpp:2147: undefined reference to `sTemplateNPC::LoadGlyphsContainer()'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/mangos/trinitycore3.3.5/TrinityCore/src/server/game/World/World.cpp:2151: undefined reference to `sTemplateNPC::LoadHumanGearContainer()'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/mangos/trinitycore3.3.5/TrinityCore/src/server/game/World/World.cpp:2155: undefined reference to `sTemplateNPC::LoadAllianceGearContainer()'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/mangos/trinitycore3.3.5/TrinityCore/src/server/game/World/World.cpp:2159: undefined reference to `sTemplateNPC::LoadHordeGearContainer()'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../scripts/libscripts.a(custom_script_loader.cpp.o): in function `AddCustomScripts()':
/home/mangos/trinitycore3.3.5/TrinityCore/src/server/scripts/Custom/custom_script_loader.cpp:25: undefined reference to `AddSC_TemplateNPC()'
collect2: error: ld returned 1 exit status
make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:168: src/server/worldserver/worldserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1520: src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

**Comment by mindsear** [comment]
I just cloned a fresh trinitycore 3.3.5 and there were no errors compiling it.
I did it on windows, never tried this script on linux.

Maybe you did something wrong. I can't figure it out right now.

Edit:
Maybe there's something wrong with 
#include "../../../src/server/scripts/Custom/TemplateNPC.h"
Try to move TemplateNPC.h to game\Accounts
And change includes for cs_realod.cpp and World.cpp to
#include "TemplateNPC.h"
